### ISSUE TITLE
setup.py is missing

### ISSUE THREAD

**Issue by hamgcho** [cyrusasfa/jtfs-gpu#9]
Hello, before I ask, I really appreciate that you generously shared the result in public.
I am really thrilled to deploy your algorithm to my data.

However there are some issues while building the environment.

![image](https://user-images.githubusercontent.com/68200616/209418845-ef41a84c-b001-4d50-aba9-76755825a650.png)

I am following the very first instruction in this repo's `README.md`, but I am lost here.
1. The thing is that, the `setup.py` is not in the `/jtfs-gpu/kymjtfs`
2. I found the` setup.py` file in the `/jtfs-gpu/` so I
   -  run it in the jtfs-gpu/
   - and copied the file to the `jtfs-gpu/kymjtfs` and run it
   but both options do not work for me.

Can you help me fix this problem?

Thank you

**Comment by cyrusvahidi** [comment]
Hello

Thank you for raising the issue!

This was an oversight on my part - I had forgot to update the installation instructions.

It should work with the updated instructions. It should have been `cd jtfs-gpu`.

**Comment by hamgcho** [comment]
Thank you for reply!

I newly pulled your codes from the repo, but still got a error when running the 
`pip install -e .` at the /`jtfs-gpu/` 
the error msg is as below : 
![image](https://user-images.githubusercontent.com/68200616/209551648-9c2466d6-bb2a-44cb-b98d-39fe5ee5f7a5.png)

Sorry to bother you, but can you help me fix this?

Thank you

**Comment by cyrusvahidi** [comment]
> Thank you for reply!
> 
> I newly pulled your codes from the repo, but still got a error when running the `pip install -e .` at the /`jtfs-gpu/` the error msg is as below : ![image](https://user-images.githubusercontent.com/68200616/209551648-9c2466d6-bb2a-44cb-b98d-39fe5ee5f7a5.png)
> 
> Sorry to bother you, but can you help me fix this?
> 
> Thank you

which version of python are you using?

**Comment by cyrusvahidi** [comment]
I am unable to reproduce your latest issue. Can you try `python setup.py develop`? I am using Python 3.8

**Comment by hamgcho** [comment]
@cyrusvahidi 
Sorry for late reply, I was in the middle of other stuff.
I again deleted the environment, and made a conda environment with python=3.8
Then the issue got resolved by just simply following the original instruction in the `readme.md`

Thank you for helping me kindly.
Also, happy new year!
